import Head from 'next/head';
import QuestionCard from 'src/components/Cards/questionCard';

function Home() {
  return (
    <>
      <Head>
        <title>Karnameh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=0"
        />
      </Head>
      <QuestionCard />
    </>
  );
}

Home.setPageConfig = {
  headerTitle: 'لیست سوالات',
};
export default Home;
